repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
#      - id: check-illegal-windows-names # coming out in the next version
      - id: check-case-conflict
      - id: check-toml
      - id: check-vcs-permalinks
default_stages:
  - commit
default_install_hook_types:
  - pre-commit
  - commit-msg
