name: Release to pypi
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          ssh-key: ${{secrets.VERSION_BUMP_SSH_PRIV_KEY}}
      - name: Install poetry
        run: pipx install poetry commitizen
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.VERSION_BUMP_PAT }}
        run: |
          git config --global user.name 'Github action'
          git config --global user.email 'githubaction@github.com'
          cz bump
          git push
          git push --tags
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish