name: Release to pypi
on:
  push:
    branches:
      - master
jobs:
  version-bump:
    name: Version bump
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install commitizen
        run: pipx install commitizen
      - name: Bump version
        run: |
          cz bump
          git config --global user.name 'Github action'
          git config --global user.email 'githubaction@github.com'
          git push --tags
  deploy:
    needs: version-bump
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish