name: Release to pypi
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install poetry
        run: pipx install poetry commitizen
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry
      - name: Bump version
        run: |
          git config --global user.name 'Github action'
          git config --global user.email 'githubaction@github.com'
          cz bump
          git push --all
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish